#!/usr/bin/env python

import sys
STDERR = sys.stderr
def excepthook(*args):
    print >> STDERR, 'caught'
    print >> STDERR, args

import re

inside = False
top = False
s = ''

for line in sys.stdin:
    matches = re.findall(r'.*\!\[[^\]]*\]\((.*?)\)', line)
    for match in matches:
        print match.lstrip('/img/')
