#!/usr/bin/env python

import sys
STDERR = sys.stderr
def excepthook(*args):
    print >> STDERR, 'caught'
    print >> STDERR, args

import re

inside = False
top = False
s = ''

for line in sys.stdin:
    if not inside and re.match(r'\s*\<article class="post"\>', line):
        top = True
    elif top and re.match(r'\s*\<\/div\>', line):
        inside = True
        top = False
    elif inside:
        if re.match(r'\s*\<div class="social bottom"\>', line):
            inside = False
            top = False
        elif not re.match(r'(\s*\<div|\s*\<\/div)', line):
            s += line

print s